export const letters = [
  { arabic: 'ب', name: 'Bā\'', makhraj: 'Inner wet parts of both lips pressed together then released.', sifaat: ['Jahr', 'Shiddah', 'Istifaal', 'Infitah', 'Ithlaq', 'Qalqalah'] },
  { arabic: 'ت', name: 'Tā\'', makhraj: 'Tip of the tongue on the gumline of the front teeth.', sifaat: ['Hams', 'Shiddah', 'Istifaal', 'Infitah', 'Ismaat'] },
  { arabic: 'ث', name: 'Thā\'', makhraj: 'Tip of the tongue against the edges of the upper teeth.', sifaat: ['Hams', 'Rikhwah', 'Istifaal', 'Infitah', 'Ismaat'] },
  { arabic: 'ج', name: 'Jīm', makhraj: 'Middle of the tongue against the hard palate.', sifaat: ['Jahr', 'Shiddah', 'Istifaal', 'Infitah', 'Ismaat', 'Qalqalah'] },
  { arabic: 'ح', name: 'Ḥā\'', makhraj: 'Middle of the throat.', sifaat: ['Hams', 'Rikhwah', 'Istifaal', 'Infitah', 'Ismaat'] },
  { arabic: 'خ', name: 'Khā\'', makhraj: 'Upper part of the throat near the mouth.', sifaat: ['Hams', 'Rikhwah', 'Isti\'laa', 'Tafkheem', 'Ismaat'] },
  { arabic: 'د', name: 'Dāl', makhraj: 'Tip of the tongue at the gumline behind front teeth.', sifaat: ['Jahr', 'Shiddah', 'Istifaal', 'Infitah', 'Qalqalah', 'Ismaat'] },
  { arabic: 'ذ', name: 'Dhāl', makhraj: 'Tip of the tongue on the edge of the upper front teeth.', sifaat: ['Jahr', 'Rikhwah', 'Istifaal', 'Infitah', 'Ismaat'] },
  { arabic: 'ر', name: 'Rā\'', makhraj: 'Tip and sides of the tongue touching upper gums.', sifaat: ['Jahr', 'Tawassut', 'Infitah', 'Takrir', 'Ithlaq', 'Inhiraf'] },
  { arabic: 'ز', name: 'Zāy', makhraj: 'Tip of the tongue near roots of upper front teeth.', sifaat: ['Jahr', 'Rikhwah', 'Istifaal', 'Infitah', 'Safir', 'Ismaat'] },
  { arabic: 'س', name: 'Sīn', makhraj: 'Tip of the tongue near gumline allowing air to flow.', sifaat: ['Hams', 'Rikhwah', 'Istifaal', 'Infitah', 'Safir', 'Ismaat'] },
  { arabic: 'ش', name: 'Shīn', makhraj: 'Middle of the tongue raised toward the palate.', sifaat: ['Hams', 'Rikhwah', 'Istifaal', 'Infitah', 'Tafashshi', 'Ismaat'] },
  { arabic: 'ص', name: 'Ṣād', makhraj: 'Tongue near gumline with sides against molars.', sifaat: ['Hams', 'Rikhwah', 'Isti\'laa', 'Itbaq', 'Safir', 'Ismaat'] },
  { arabic: 'ض', name: 'Ḍād', makhraj: 'Sides of the tongue against upper molars.', sifaat: ['Jahr', 'Rikhwah', 'Isti\'laa', 'Itbaq', 'Istitalah', 'Ismaat'] },
  { arabic: 'ط', name: 'Ṭā\'', makhraj: 'Tip of tongue at gumline with back raised.', sifaat: ['Jahr', 'Shiddah', 'Isti\'laa', 'Itbaq', 'Qalqalah', 'Ismaat'] },
  { arabic: 'ظ', name: 'Ẓā\'', makhraj: 'Tip of tongue on edges of upper teeth.', sifaat: ['Jahr', 'Rikhwah', 'Isti\'laa', 'Itbaq', 'Ismaat'] },
  { arabic: 'ع', name: '\'Ayn', makhraj: 'Middle of the throat.', sifaat: ['Jahr', 'Tawassut', 'Istifaal', 'Infitah', 'Ismaat'] },
  { arabic: 'غ', name: 'Ghayn', makhraj: 'Upper throat close to Khā\'.', sifaat: ['Jahr', 'Rikhwah', 'Isti\'laa', 'Infitah', 'Ismaat'] },
  { arabic: 'ف', name: 'Fā\'', makhraj: 'Lower lip touching upper front teeth.', sifaat: ['Hams', 'Rikhwah', 'Istifaal', 'Infitah', 'Ithlaq'] },
  { arabic: 'ق', name: 'Qāf', makhraj: 'Back of tongue against soft palate.', sifaat: ['Jahr', 'Shiddah', 'Isti\'laa', 'Infitah', 'Qalqalah', 'Ismaat'] },
  { arabic: 'ك', name: 'Kāf', makhraj: 'Back of tongue against hard palate.', sifaat: ['Hams', 'Shiddah', 'Istifaal', 'Infitah', 'Ismaat'] },
  { arabic: 'ل', name: 'Lām', makhraj: 'Tip of tongue on gumline, sides touching molars.', sifaat: ['Jahr', 'Tawassut', 'Istifaal', 'Infitah', 'Ithlaq', 'Inhiraf'] },
  { arabic: 'م', name: 'Mīm', makhraj: 'Lips closed with nasal flow.', sifaat: ['Jahr', 'Tawassut', 'Istifaal', 'Infitah', 'Ithlaq', 'Ghunnah'] },
  { arabic: 'ن', name: 'Nūn', makhraj: 'Tip of tongue at gumline with nasal sound.', sifaat: ['Jahr', 'Tawassut', 'Istifaal', 'Infitah', 'Ghunnah', 'Ithlaq'] },
  { arabic: 'و', name: 'Wāw', makhraj: 'Rounded lips.', sifaat: ['Jahr', 'Rikhwah', 'Istifaal', 'Infitah', 'Lin'] },
  { arabic: 'ه', name: 'Hā\'', makhraj: 'Middle of the throat.', sifaat: ['Hams', 'Rikhwah', 'Istifaal', 'Infitah', 'Ismaat'] },
  { arabic: 'ء', name: 'Hamzah', makhraj: 'Deepest part of the throat.', sifaat: ['Jahr', 'Shiddah', 'Istifaal', 'Infitah', 'Ismaat'] },
  { arabic: 'ي', name: 'Yā\'', makhraj: 'Middle of tongue raised toward palate.', sifaat: ['Jahr', 'Rikhwah', 'Istifaal', 'Infitah', 'Lin'] },
];

export const sifaatColors = {
  'Jahr': 'bg-emerald-100 text-emerald-800',
  'Hams': 'bg-sky-100 text-sky-800',
  'Shiddah': 'bg-red-100 text-red-800',
  'Rikhwah': 'bg-orange-100 text-orange-800',
  'Tawassut': 'bg-yellow-100 text-yellow-800',
  'Istifaal': 'bg-purple-100 text-purple-800',
  "Isti'laa": 'bg-pink-100 text-pink-800',
  'Infitah': 'bg-indigo-100 text-indigo-800',
  'Itbaq': 'bg-rose-100 text-rose-800',
  'Ithlaq': 'bg-teal-100 text-teal-800',
  'Ismaat': 'bg-slate-100 text-slate-700',
  'Qalqalah': 'bg-amber-100 text-amber-800',
  'Safir': 'bg-cyan-100 text-cyan-800',
  'Ghunnah': 'bg-violet-100 text-violet-800',
  'Tafkheem': 'bg-pink-100 text-pink-800',
  'Tafashshi': 'bg-lime-100 text-lime-800',
  'Takrir': 'bg-fuchsia-100 text-fuchsia-800',
  'Inhiraf': 'bg-green-100 text-green-800',
  'Lin': 'bg-blue-100 text-blue-800',
  'Istitalah': 'bg-red-100 text-red-800',
};
